export const ALL_WAREHOUSES_REQUEST = 'ALL_WAREHOUSES_REQUEST';

export const FETCH_WAREHOUSE_DETAILS_REQUEST = 'FETCH_WAREHOUSE_DETAILS_REQUEST';
export const FETCH_WAREHOUSE_DETAILS_SUCCESS = 'FETCH_WAREHOUSE_DETAILS_SUCCESS';
export const FETCH_WAREHOUSE_DETAILS_FAILURE = 'FETCH_WAREHOUSE_DETAILS_FAILURE';

export const UPDATE_WAREHOUSE_REQUEST = 'UPDATE_WAREHOUSE_REQUEST';
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS';
export const UPDATE_WAREHOUSE_RESET = "UPDATE_WAREHOUSE_RESET";
export const UPDATE_WAREHOUSE_FAILURE = 'UPDATE_WAREHOUSE_FAILURE';

export const SEARCH_WAREHOUSES_REQUEST = 'SEARCH_WAREHOUSES_REQUEST';
export const SEARCH_WAREHOUSES_SUCCESS = 'SEARCH_WAREHOUSES_SUCCESS';
export const SEARCH_WAREHOUSES_FAILED = 'SEARCH_WAREHOUSES_FAILED';

export const FILTER_WAREHOUSE_REQUEST = 'FILTER_WAREHOUSE_REQUEST';
export const FILTER_WAREHOUSE_SUCCESS = 'FILTER_WAREHOUSE_SUCCESS';
export const FILTER_WAREHOUSE_FAILURE = 'FILTER_WAREHOUSE_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

